music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:create, :new, :destroy, :show]
  resource :session, only: [:create, :destroy, :new]
  resources :bands, except: [] do
    resources :album, only: [:new]
  end
  resources :album, only: [:create, :show, :update, :destroy, :edit]
end

music_app/app/models/album.rb
class Album < ApplicationRecord

    validates :title, presence: true
    validates :band_id, presence: true, 

    belongs_to :band,
        :primary_key: :id,
        :foreign_key: :band_id,
        :class_name: :Band
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord

    validates :name, presence: true

    has_many :albums,
        primary_key: :id,
        foreign_key: :band_id,
        class_name: :Album
end

music_app/app/models/user.rb
class User < ApplicationRecord

    validates :email, uniqueness: true, presence: true
    validates :password_digest, presence: true
    validates :password, allow_nil: true, length: {minimum: 6}
    validates :session_token, presence: true, uniqueness: true
    attr_reader :password
    after_initialize :ensure_session_token

    def self.generate_session_token
        SecureRandom::urlsafe_base64
    end

    def reset_session_token! 
        self.session_token = User.generate_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end

    def self.find_by_credentials(email, password)
        @user = User.find_by(email: email)
        if @user && @user.is_password?(password)
            return @user
        else
            return nil
        end
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def is_password?(password)
        password_object = BCrypt::Password.new(self.password_digest)
        password_object.is_password?(password)
    end

end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

    def new
        render :new
    end

    def create
        @album = Album.new(params)
        if @album.save
            redirect_to album_url(@album)
        else
            flash.now[:errors] = @album.errors.full_messages
            render :new
        end
    end

    def show
        @album = Album.find_by(:id [params[:id]])
        render :show
    end

    def update
        @album = album.find_by(:id [params[:id]])
        if @album.update_atributes(band_params)
            redirect_to album_url(@album)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    def destroy
        @album = album.find_by(:id [params[:id]])
        @album.destroy
        redirect_to bands_url

    end


    private
    def album_params
        params.require(:album).permit(:title, :year, :studio, :band_id)
    end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token] )
    end

    def logged_in?
        !!current_user
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
        @current_user= user
    end

    def logout!
        current_user.reset_session_token!
        session[:session_token] = nil
        @current_user = nil
    end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController

    def index
        @bands = Band.all
        render :index
    end

    def create
        @band = Band.new(band_params)

        if @band.save
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :new
        end
    end

    def new
        render :new
    end

    def edit
        render :edit
    end

    def show
        @band = Band.find(params[:id])
        render :show
    end

    def update
        @band = Band.find_by(:id [params[:id]])
        if @band && @band.update_atributes(band_params)
            redirect_to band_url(@band)
        else
            flash.now[:errors] = @band.errors.full_messages
            render :edit
        end
    end

    def destroy
        @band = Band.find_by(:id [params[:id]])
        @band.destroy
        redirect_to bands_url
    end

    private

    def band_params
        params.require(:band).permit(:name)
    end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        render :new
    end

    
    def create
        @user = User.find_by_credentials(params[:user][:email],params[:user][:password])
        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = ["Incorrent email/password"]
            render :new
        end
            
    end

    def destroy
        logout!
        redirect_to new_session_url
    end


end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        render :new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            login!(@user)
            redirect_to user_url(current_user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def show 
        @user = current_user
        render :show
    end

    def destroy
        @user = current_user
    end

    private
    def user_params
        params.require(:user).permit(:email, :password)
    end 


end

music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

music_app/app/helpers/users_helper.rb
module UsersHelper
end

music_app/app/views/bands/index.html.erb
<% @bands.each do |band| %>
    <h3>
    <a href='<%=band_url(band)%>'> <%= band.name%> </a>
    </h3>
    <br>
<%end%>
<a href="<%= new_band_url %>"> Add another band!</a>

music_app/app/views/bands/new.html.erb
<form action="<%= bands_url %>" method="POST"> 
    <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>

    <label for="band">Band: </label>
    <input id="band" type="text" name="band[name]" >
    <br>

    <input type="submit" value=" add band">
    <br>

    <% if flash[:errors]%>
        <% flash[:errors].each do |error| %>
            <%= error %>
            <br>
        <%end%>
    <%end%>

</form>

music_app/app/views/bands/show.html.erb
<h3><%= @band.name%> </h3>
<form action='<%=band_url%>' method="POST" >
            <input type='hidden' name='_method' value='DELETE'>
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type='submit' value='Remove Band'>
<br>

<a href="<%= bands_url %>">Return to bands</a>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="header"> 

      <div></div>
      MUSIC APP
      
      <div id=login_info>
        <% if logged_in?%>
          <p>Welcome <%= current_user.email%></p>
          <form action='<%=session_url%>' method="POST" >
            <input type='hidden' name='_method' value='delete'>
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

            <input type='submit' value='Log Out'>
          </form>
        

          <%else%>
            <a href="<%= new_user_url %>" >New account</a>
            <br>
            <a href="<%= new_session_url %>">Log in</a>
          <%end%>
      </div>
    </h1>

    <%= yield %>
  </body>
</html>

music_app/app/views/users/new.html.erb
<h2>Create New Account:</h2>
<form action="<%= users_url %>" method="POST"> 
    <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>

    <label for="email">Email: </label>
    <input id="email" type="text" name="user[email]" >
    <br>
    
    <label for="password">Password: </label>
    <input id="password" type = "password" name="user[password]">
    <br>

    <input type="submit" value="Create new user">
    <br>

    <% if flash[:errors]%>
        <% flash[:errors].each do |error| %>
            <%= error %>
            <br>
        <%end%>
    <%end%>

</form>

music_app/app/views/users/show.html.erb
<h3><%= current_user.email%> </h3>